server:
  port: 10010

spring:
  mvc:
    view:
      suffix: .html

  username: zjallinpaytest
  password: zjallinpaytest

  datasource:
#    url: jdbc:oracle:thin:@10.48.1.253:1521:ora11g
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: zjallinpaytest
#    password: zjallinpaytest
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 200
      max-wait: 6000
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      max-pool-prepared-statement-per-connection-size: 20
      url: jdbc:oracle:thin:@10.48.1.253:1521:ora11g
      driver-class-name: oracle.jdbc.OracleDriver
      username: zjallinpaytest
      password: zjallinpaytest

#mybatis:
#  mapper-locations: classpath:/mappers/*.xml
#  type-aliases-package: com.venus.tspro.entity
logging:
  classpath: log4j2.xml
  level:
    com.venus.tspro.dao: debug
